"""tracks search_index

Revision ID: 0e5ddc09e7e6
Revises: bdc78a272fb3
Create Date: 2026-07-29 20:57:35.797687
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0e5ddc09e7e6'
down_revision: str | None = 'bdc78a272fb3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soundcloud_imported', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soundcloud_imported_url'))
        batch_op.create_index(batch_op.f('ix_soundcloud_imported_url'), ['url'], unique=True)

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_index', sa.String(length=600), nullable=True))
        batch_op.create_index(batch_op.f('ix_tracks_search_index'), ['search_index'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_search_index'))
        batch_op.drop_column('search_index')

    with op.batch_alter_table('soundcloud_imported', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_soundcloud_imported_url'))
        batch_op.create_index(batch_op.f('ix_soundcloud_imported_url'), ['url'], unique=False)

    # ### end Alembic commands ###
