"""telegram channel sources and imports

Revision ID: 634a457eb4d6
Revises: 7888435ef558
Create Date: 2026-07-12 12:26:27.397237
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '634a457eb4d6'
down_revision: str | None = '7888435ef558'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channel_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('found_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_channel_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('original_title', sa.String(length=512), nullable=True),
    sa.Column('detected_title', sa.String(length=256), nullable=True),
    sa.Column('detected_artist', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['telegram_channel_sources.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'message_id', name='uq_tgchan_source_message')
    )
    with op.batch_alter_table('telegram_channel_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_channel_imports_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_channel_imports_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_channel_imports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_channel_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_channel_imports_status'))
        batch_op.drop_index(batch_op.f('ix_telegram_channel_imports_source_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_channel_imports_message_id'))

    op.drop_table('telegram_channel_imports')
    op.drop_table('telegram_channel_sources')
    # ### end Alembic commands ###
