"""genres + artist card fields

Revision ID: 66dd24c3fa53
Revises: 8e5f9a2b3c4d
Create Date: 2026-07-23 22:16:56.523144
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '66dd24c3fa53'
down_revision: str | None = '8e5f9a2b3c4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genres_parent_id'), ['parent_id'], unique=False)

    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', 'genre_id')
    )
    with op.batch_alter_table('artist_genres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_genres_genre_id'), ['genre_id'], unique=False)

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('aliases', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mbid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('deezer_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('youtube_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('source_status', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_artists_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_artists_source_status'), ['source_status'], unique=False)
        batch_op.create_unique_constraint('uq_artists_mbid', ['mbid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artists_mbid', type_='unique')
        batch_op.drop_index(batch_op.f('ix_artists_source_status'))
        batch_op.drop_index(batch_op.f('ix_artists_country'))
        batch_op.drop_column('source_status')
        batch_op.drop_column('youtube_url')
        batch_op.drop_column('deezer_id')
        batch_op.drop_column('mbid')
        batch_op.drop_column('aliases')
        batch_op.drop_column('country')
        batch_op.drop_column('banner_url')

    with op.batch_alter_table('artist_genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_genres_genre_id'))

    op.drop_table('artist_genres')
    with op.batch_alter_table('genres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genres_parent_id'))

    op.drop_table('genres')
    # ### end Alembic commands ###
