"""app_settings runtime flags

Revision ID: 7888435ef558
Revises: b417f0084a03
Create Date: 2026-07-12 11:58:36.937140
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7888435ef558'
down_revision: str | None = 'b417f0084a03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
