"""contests — конкурсы с розыгрышем Premium (SPEC-2.0 §28)

Revision ID: a367a749c438
Revises: fba9cf9d09e3
Create Date: 2026-07-25 23:49:16.189695
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a367a749c438'
down_revision: str | None = 'fba9cf9d09e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('banner_text', sa.String(length=160), nullable=False),
    sa.Column('prize_days', sa.Integer(), nullable=False),
    sa.Column('required_channel', sa.String(length=64), nullable=True),
    sa.Column('required_referrals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('winner_user_id', sa.Integer(), nullable=True),
    sa.Column('drawn_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['winner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contest_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('referrals_at_join', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contest_id', 'user_id', name='uq_contest_participant')
    )
    with op.batch_alter_table('contest_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_participants_contest_id'), ['contest_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contest_participants_user_id'), ['user_id'], unique=False)


def downgrade() -> None:
    with op.batch_alter_table('contest_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_participants_user_id'))
        batch_op.drop_index(batch_op.f('ix_contest_participants_contest_id'))

    op.drop_table('contest_participants')
    op.drop_table('contests')
    # ### end Alembic commands ###
