"""youtube sources and imports

Revision ID: b417f0084a03
Revises: b3e91a7c42d0
Create Date: 2026-07-11 22:16:20.902040
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b417f0084a03'
down_revision: str | None = 'b3e91a7c42d0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('found_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('youtube_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('video_title', sa.String(length=512), nullable=True),
    sa.Column('detected_title', sa.String(length=256), nullable=True),
    sa.Column('detected_artist', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['youtube_sources.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'video_id', name='uq_source_video')
    )
    with op.batch_alter_table('youtube_imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_imports_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtube_imports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_youtube_imports_video_id'), ['video_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_imports_video_id'))
        batch_op.drop_index(batch_op.f('ix_youtube_imports_status'))
        batch_op.drop_index(batch_op.f('ix_youtube_imports_source_id'))

    op.drop_table('youtube_imports')
    op.drop_table('youtube_sources')
    # ### end Alembic commands ###
