"""add tracks.tg_file_id

Revision ID: f87cfcd94b80
Revises: d01cfc648f91
Create Date: 2026-07-11 10:46:59.572398
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f87cfcd94b80'
down_revision: str | None = 'd01cfc648f91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tg_file_id', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_column('tg_file_id')

    # ### end Alembic commands ###
